---
- name: apt 卸载 ntp
  shell: 'apt remove -y ntp'
  when: 'ansible_distribution in ["Ubuntu","Debian"]' 
  ignore_errors: true

- name: yum 卸载 ntp
  shell: 'yum remove -y ntp'
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon","Aliyun"]'
  args:
      warn: false
  ignore_errors: true

- name: Yum Install Chronyd
  yum: name=chrony state=present


- name: Configure Chrony Server
  template: src=server.conf.j2 dest=/etc/chrony.conf
  when: 'inventory_hostname == groups.chrony[0]'

- name: Configure Chrony Client
  template: src=client.conf.j2 dest=/etc/chrony.conf
  when: 'inventory_hostname != groups.chrony[0]'

- name: 开机启用chronyd服务
  shell: systemctl enable chronyd
  ignore_errors: true

- name: 开启chronyd服务
  shell: systemctl daemon-reload && systemctl restart chronyd
  ignore_errors: true
  tags: restart_chronyd

- name: 以轮询的方式等待chronyd服务启动
  shell: "systemctl is-active chronyd.service"
  register: svc_status
  until: '"active" in svc_status.stdout'
  retries: 3
  delay: 3
  tags: restart_chronyd

